version: '3'

services:
  api:
    restart: always
    container_name: banaspati-api
    build: .
    image: repodevs/banaspati:1.0
    ports:
      - "8338:8338"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    env_file: ./.env.docker
    command:
       gunicorn -w 1 -b 0.0.0.0:8338 core.wsgi:app

  nginx:
    restart: always
    container_name: banaspati-nginx
    build: ./deployment/nginx
    image: repodevs/banaspati:nginx
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx/sites-enabled:/etc/nginx/conf.d
    depends_on:
      - api

  postgres:
    restart: always
    container_name: banaspati-postgres
    build: ./deployment/postgres
    image: repodevs/banaspati:postgres
    ports:
      - "5432:5432"
  #  volumes:
  #    - ./postgres/db:/var/lib/postgresql
